baseURL = "https://theclosingbox.com/"
languageCode = "en-us"
title = "the closing box"
theme="hugo_theme_pickles"

[params]
  paginate = 10
  twitter = "timjglynn"
  favicon = "/images/favicon.ico"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "about"
    url = "/about"
    weight = 2
