baseURL = "https://theclosingbox.com/"
title = "the closing box"
theme="hugo-book"

[params]
  BookTheme = 'light'
  BookToC = true
  BookFavicon = 'images/favicon.ico'
  BookSection = '*'
  # BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false



# [[menu.after]]
#     name = "home"
#     url = "/"
#     weight = 1

# [[menu.after]]
#     name = "about"
#     url = "/about"
#     weight = 2
